#!/usr/bin/env bash
# Setup local CLI access to the personal openclaw gateway.
#
# This script:
#   1. Installs Python dependencies (websockets, cryptography) locally
#   2. Copies openclaw-chat to ~/.local/bin/
#   3. Retrieves the gateway token from the remote server and saves it to ~/.openclaw/.env
#   4. Prints SSH tunnel setup instructions
#
# Usage: ./scripts/setup-cli.sh [ssh-host]
# Requires: .env with HETZNER_SSH_HOST (or pass ssh-host as first arg)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

# Read a single value from .env without sourcing (safe with special characters)
_env_get() {
  local key="$1" file="$2"
  grep -m1 "^${key}=" "$file" 2>/dev/null | cut -d= -f2- || true
}

ENV_FILE="$REPO_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found. Copy .env.template to .env and fill in credentials."
  exit 1
fi

SSH_HOST="${1:-$(_env_get HETZNER_SSH_HOST "$ENV_FILE")}"
SSH_HOST="${SSH_HOST:-hetzner-main}"

# Read optional CLI overrides from .env
OPENCLAW_GATEWAY_TOKEN="$(_env_get OPENCLAW_GATEWAY_TOKEN "$ENV_FILE")"
OPENCLAW_GATEWAY_PORT="$(_env_get OPENCLAW_GATEWAY_PORT "$ENV_FILE")"
OPENCLAW_SESSION_KEY="$(_env_get OPENCLAW_SESSION_KEY "$ENV_FILE")"
OPENCLAW_ENV_DIR="$HOME/.openclaw"
OPENCLAW_ENV_FILE="$OPENCLAW_ENV_DIR/.env"

echo "=== Setting up openclaw CLI access ==="

# ------------------------------------------------------------------
# 1. Check uv is available (used for auto-managing script dependencies)
# ------------------------------------------------------------------
echo ""
echo "→ Checking uv..."
if ! command -v uv &>/dev/null; then
  echo "  ⚠ uv not found. Install it: curl -LsSf https://astral.sh/uv/install.sh | sh"
  echo "    Then re-run this script."
  exit 1
fi
echo "  ✓ uv found — dependencies will be managed automatically"

# ------------------------------------------------------------------
# 2. Install openclaw-chat to ~/.local/bin/
# ------------------------------------------------------------------
echo ""
echo "→ Installing openclaw-chat to ~/.local/bin/ ..."
mkdir -p "$HOME/.local/bin"
cp "$SCRIPT_DIR/openclaw-chat" "$HOME/.local/bin/openclaw-chat"
chmod +x "$HOME/.local/bin/openclaw-chat"
echo "  ✓ Installed at ~/.local/bin/openclaw-chat"

# ------------------------------------------------------------------
# 3. Retrieve gateway token from remote and save to ~/.openclaw/.env
# ------------------------------------------------------------------
echo ""
echo "→ Fetching gateway token from $SSH_HOST ..."
mkdir -p "$OPENCLAW_ENV_DIR"

# Try to retrieve the token from the gateway config on the remote
GATEWAY_TOKEN=""
if GATEWAY_TOKEN=$(ssh "$SSH_HOST" "openclaw config get gateway.auth.token 2>/dev/null" 2>/dev/null); then
  GATEWAY_TOKEN="${GATEWAY_TOKEN//[$'\r\n']}"  # strip newlines
  echo "  ✓ Retrieved gateway token"
elif [ -n "${OPENCLAW_GATEWAY_TOKEN:-}" ]; then
  GATEWAY_TOKEN="$OPENCLAW_GATEWAY_TOKEN"
  echo "  ✓ Using token from local .env"
else
  echo "  ⚠ Could not retrieve gateway token automatically."
  echo "    Run on the server: openclaw config get gateway.auth.token"
  echo "    Then add it to ~/.openclaw/.env as OPENCLAW_GATEWAY_TOKEN=<token>"
fi

# Write ~/.openclaw/.env
GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-18789}"
SESSION_KEY="${OPENCLAW_SESSION_KEY:-home}"

cat > "$OPENCLAW_ENV_FILE" <<EOF
# openclaw CLI configuration — auto-generated by setup-cli.sh
OPENCLAW_GATEWAY_TOKEN=${GATEWAY_TOKEN}
OPENCLAW_GATEWAY_PORT=${GATEWAY_PORT}
OPENCLAW_SESSION_KEY=${SESSION_KEY}
OPENCLAW_TIMEOUT=60
EOF
echo "  ✓ Saved configuration to $OPENCLAW_ENV_FILE"

# ------------------------------------------------------------------
# 4. Done
# ------------------------------------------------------------------
echo ""
echo "=== All set! ==="
echo ""
echo "The SSH tunnel starts automatically when needed — no manual setup required."
echo ""
echo "  Test connection:  openclaw-chat --health"
echo "  Send a message:   openclaw-chat \"Hello from the terminal!\""
echo "  Interactive mode: openclaw-chat"
echo ""
echo "SSH host used for tunnel: ${SSH_HOST}"
echo "Session key:              ${GATEWAY_PORT}"
